### ISSUE TITLE
Doesn’t work. 

### ISSUE THREAD

**Issue by iammanpreetsingh** [Renaitare/Notations#2] opened 2020-04-14 08:29 UTC
Nothing happens when I double tap the stausbar. It just dims my homescreen. I tap and hold the screen but still nothing.

iPhone 8
iOS13.3 checkra1n

**Comment by iD7me** [comment] 2020-04-14 17:55
After dimmed screen tap and hold on the middle of the screen it should work now.

**Comment by tale** [comment] 2020-04-14 18:15
Duplicate of #1 lmao.... yeah just make sure to tap and hold to create a note!

**Closed as completed by tale** 2020-04-14 18:15 UTC
